### ISSUE TITLE
Add file and http protocol to follow link function.

### ISSUE THREAD

**Issue by GordianDziwis** [fcpg/vim-waikiki#1]
Such a nice minimal wiki, it would be a shame if someone requests some features ;)
Like being able to handle different protocols with the follow link function.
```
[namespace lookup for RDF developers](http://prefix.cc/) <- open in browser
[Some File](file:///home/user/test.scala) <- open in vim
```

**Comment by fcpg** [comment]
Haha, yeah it goes a bit against the minimalist spirit of the plugin. You might be able to already do it by tweaking configuration, eg. calling `waikiki#FollowLink({'action':'YourCmd'})` with a user command of yours that can check the scheme and act accordingly.
