### ISSUE TITLE
Account the hyphen symbol ('-') when creating a link from the word under cursor

### ISSUE THREAD

**Issue by m1t0z** [fcpg/vim-waikiki#10]
Hi. 

First let me thank you for this wonderful minimalistic plugin.
I've finally decided to track my notes within VIM and so far this plugin looks exactly what i was looking for.

The only thing currently that works against my expectations is the fact that the hyphen symbol is not accounted when creating a link from the word under cursor.

For example, I have the following line:
```
vim-cheat-sheet - here are my personal VIM cheat sheet
```
The cursor is on the first word of the line, i.e. `vim`.
I press <LocalLeader><Return> (which is by default mapped to the `<Plug>(waikikiFollowLink)`) and expect that the file `vim-cheat-sheet.md` will be created. However the created file have a much shorter name: `vim.md`.

I've learned that i can use the VISUAL mode, to achieve the desired behaviour, but i really would like to save some keystrokes :)

I've shortly looked to the implementation of the plugin and found the reason of the described behaviour:

```
function! waikiki#FollowLink(...) abort
  ...
  let name    = get(options, 'name', expand('<cword>'))
  ...
```
Affect of the `<cword>` could be customized by the `iskeyword` variable. Thus my current (and far from ideal) workaround is to add the following settings to my *.vimrc* file in order to account the hyphen symbol.
```
let g:waikiki_roots = [ <PATH_TO_NOTES_ROOT> ]
autocmd BufRead,BufNewFile <PATH_TO_NOTES_ROOT>/* setlocal iskeyword+=- 
```
I believe it would be nicer to have a setting with a similar affect inside the plugin itself, so it will affect only the plugin functionality (even more precisely,  only the functionality of the waikiki#FollowLink function inside the plugin) rather than the rest of VIM functionality for the all files under the `<PATH_TO_NOTES_ROOT>` directory.

Overall I ask you to consider to add a new global setting for the plugin, which will allow to specify (at least to extend) the symbols that will be accounted as part of the word during the link creation. I think it would be also nice if hyphen symbol would be there by default, because it is kind-a common to use this symbol as a word separator inside the file names.

Best regards, 
Dmitry.

**Comment by fcpg** [comment]
Thanks for the kind words, and for the detailed description.

As you found out, my advice (and the way I do it too) would be to use visual mode. However, I realize this might get annoying after a while if you got a lot of hyphenated pages.

I'm a bit busy right now, but I will definitely give it a look in the next few days (hopefully this week-end or next week).

**Comment by fcpg** [comment]
Pushed a commit that add the `g:waikiki_use_word_regex` and `g:waikiki_word_regex` options, solving this issue.

**Comment by m1t0z** [comment]
Thank you very much! Checked your solution for my local vim installation - works perfectly!
