### ISSUE TITLE
How can I customize waikiki#FollowLink?

### ISSUE THREAD

**Issue by ahmedelgabri** [fcpg/vim-waikiki#13]
I have some folders were the structure looks like this

```
<year>
|_ <month>
  |_ <day>
    |_ <timestamp>-<title>.md
```

Is there is a way to hook into `waikiki#FollowLink` or override it, so I can add the timestamp always? Currently, I can't find a way to do this & it's very tedious to create a file manually, then also manually update `index.md` to point to the right path.

**Comment by fcpg** [comment]
Hello,
I just pushed a commit with the new 'g:waikiki_targetsdict_func' option, with an example similar to what you want to do in the doc.
I don't know if you wanted to create the whole directory structure when following, but that should be doable too.

**Comment by ahmedelgabri** [comment]
I had a look & copied the example from the docs & that's exactly what I wanted, thanks!
