### ISSUE TITLE
Question: How should I exactly use tags?

### ISSUE THREAD

**Issue by Skabit** [fcpg/vim-waikiki#14]
Hi,

I read documentation and I can't achieve generate tags. In my vimrc file I have the next lines:

      let g:waikiki_roots = ['~/vimwiki/']
      let maplocalleader = "\<F7>"
      let g:waikiki_default_maps = 1

So, I type on my index file `:tag1:tag2`, then on normal mode `:WaikikiTags ` and nothing happens, I try with F7 + T and again nothing happens. 

On my waikiki folder no appears tags file and I don't understand the workflow with tags.

Please, Can you teach me how to use tags with Waikiki?

**Comment by fcpg** [comment]
Hello,

Just add a line into your file with `:tag1:tag2:tag3:`, with a leading and trailing colon. The line should not contain anything else (except optional blanks). You must also have the `ctags` binary into your path. Then just run the vim command `:WaikikiTags`

Also, for technical reasons, the number of tags is currently limited to six per line.

**Comment by Skabit** [comment]
Oh my gosh. Realy sorry, I miss `ctags`. Thanks, now I will learn ctags. Congratulations for the pluggin.
