### ISSUE TITLE
How to search ?

### ISSUE THREAD

**Issue by carugnom** [fcpg/vim-waikiki#16]
The documentation doesn't show a way to search text in the wiki.
Is there a way to do it ?
Also, how could I search for tags ?
That information should be added to the documentation, even if there is no search function since it's an expected one
Thanks !

**Comment by fcpg** [comment]
There is nothing special for searching vimwiki files, you can do it with the standard vim tools eg. `vimgrep` or `tags`.
If there is enough demand for extra documentation on using tags with waikiki, I might add a few paragraphs, but it should be straightforward if you already used tags before.
