### ISSUE TITLE
Variable names in Vim doc file don't match those used by the plugin

### ISSUE THREAD

**Issue by axvr** [fcpg/vim-waikiki#3]
First I'd like to say thanks for making such an excellent plugin, it fits my use-cases perfectly.

The only issue I've had with it so far is that the names of a couple of the option variables mentioned in the Vim doc file, don't actually match the variable names used by the plugin source code.

| Vim doc | Source code |
|---|---|
| [`g:waikiki_roots`](https://github.com/fcpg/vim-waikiki/blob/4fc4e9300b1ad501ef4a15af91759116e36a4924/doc/waikiki.txt#L143) | [`g:waikiki_wiki_roots`](https://github.com/fcpg/vim-waikiki/blob/4fc4e9300b1ad501ef4a15af91759116e36a4924/autoload/waikiki.vim#L31) |
| [`g:waikiki_patterns`](https://github.com/fcpg/vim-waikiki/blob/4fc4e9300b1ad501ef4a15af91759116e36a4924/doc/waikiki.txt#L149) | [`g:waikiki_wiki_patterns`](https://github.com/fcpg/vim-waikiki/blob/4fc4e9300b1ad501ef4a15af91759116e36a4924/autoload/waikiki.vim#L30) |

**Comment by fcpg** [comment]
Thanks for reporting it; I have added `g:waikiki_roots` and `g:waikiki_patterns` as aliases for their counterparts, so both should work.

**Comment by axvr** [comment]
Excellent thank you, it works perfectly now.
