### ISSUE TITLE
Write buffer before following link

### ISSUE THREAD

**Issue by tlvince** [fcpg/vim-waikiki#5]
If the buffer has pending changes when invoking `Plug(waikikiFollowLink)`, vim will throw

```
Error detected while processing function waikiki#FollowLink:
line   69:
E37: No write since last change (add ! to override)
```

It'd be nice if waikiki could write the buffer itself first (perhaps configurable).

This would also help creating new links more fluid, e.g. visually selecting `Hello World`, then hitting `<LocalLeader><Return>` (helpfully) creates the link `[Hello World](Hello_World.md)`, but bails out when trying to edit it.

**Comment by tlvince** [comment]
Following your suggestion in #1, I've managed to get this working via custom config:

```viml
function! mywaikiki#SetupBuffer() abort
  nmap <buffer><silent> <cr> :call waikiki#FollowLink({
  \ 'action': 'WaikikiWriteFollowLink',
  \ 'create': 'WaikikiWriteFollowLink'
  \ })<cr>
endfun

augroup Waikiki
  au!
  autocmd User setup call mywaikiki#SetupBuffer()
augroup END

function! mywaikiki#WriteFollowLink(target) abort
  write
  execute 'edit' a:target
endfun

com! -nargs=? -bar -complete=dir WaikikiWriteFollowLink call mywaikiki#WriteFollowLink(<f-args>)
```

It's a bit round about, but seems to work.

Your call whether anything needs to be done :) Maybe adding this as an example is enough.

**Comment by fcpg** [comment]
Most people set the 'hidden' option, so I'm reluctant to adding code or another option in the plugin for such a tiny part of the users (I already tend to add too many options!). 

Your solution is fine, I try to make things customizable so that users can do what you did. I'll close this one, and maybe drop a line in the docs about it.

**Comment by ErickChacon** [comment]
You could use `set autowriteall` in your config file or `setlocal autowriteall` for markdown filetype.
