### ISSUE TITLE
Question: How should I exactly use this plugin?

### ISSUE THREAD

**Issue by yujinyuz** [fcpg/vim-waikiki#6]
Coming from `vimwiki`, all I have to do is `<leader>ww` and  it opens the wiki index located on the folder I specified in my config.

Just wanted to know how exactly do I use this plugin?

**Comment by fcpg** [comment]
It's described in the docs: https://github.com/fcpg/vim-waikiki/blob/master/doc/waikiki.txt

Eg.

- add `let g:waikiki_roots = ['~/vimwiki/']` in your vimrc
- from shell: `cd ~/vimwiki/; vim index.md`
- write your doc (markdown by default)
- when cursor is on a new markdown link (eg. `[foo]`), hit `<LocalLeader><Return>`: this will "follow" the link and create a new empty doc 'foo', as well as completing the markdown link in the former buffer (`[foo](foo)`).

Check the other mappings for navigation. If you would like to open your `index.md` from some mapping, you can easily create it (eg. `nn <Leader>ww :e ~/vimwiki/index.md<cr>`.

**Comment by yujinyuz** [comment]
Ahh. Thanks! Makes much sense now.

What happens when I have two root folders?

let g:waikiki_roots = ['~/wiki1', '~/wiki2']

Does it do anything special?

**Comment by fcpg** [comment]
Each folder in the array will be recognized as the root of a different wiki; that way, you can have several wikis--say, one for your work, one for personal topics etc.

Specifically, this means:

- editing files under one of the roots will have the buffer-local mappings,
- using the go-up navigation mapping won't go past that root,
- and tags file will be created there (if you create them).

**Comment by yujinyuz** [comment]
Thanks for answering my questions! Really appreciate it
