### ISSUE TITLE
Setting g:waikiki_create_type to '' doesn't work

### ISSUE THREAD

**Issue by miffi** [fcpg/vim-waikiki#8]
Hello, title hopefully explains my problem.

I am getting this error after using the default keybind `<localleader><enter>` to create a new wiki file.

```Error detected while processing function waikiki#FollowLink:
line   55:
E691: Can only compare List with List
E15: Invalid expression: targetlist == ''
```

**Comment by fcpg** [comment]
Sorry for not getting back sooner, been quite busy lately. I will look into it.

**Comment by clownfetus** [comment]
You can fix this by removing that if statement; afaik it doesn't do anything.

**Comment by fcpg** [comment]
I just pushed a fix. Let me know if you still got the problem.

**Comment by miffi** [comment]
The problem's fixed now. I can see the prompt. Thanks ^^
